brain_two/brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include('todos.urls')),
    
]

brain_two/todos/urls.py
from django.shortcuts import render
from .models import TodoList
from django.urls import path
from .views import todo_list_list, todo_list_detail, todo_list_add


def todo_list_list(request):
    todo_lists = TodoList.objects.all()
    context = {'todo_lists': todo_lists}
    return render(request, 'todos/todo_list_list.html', context)

app_name = 'todos'

urlpatterns = [
    path('', todo_list_list, name='todo_list_list'),
    path('<int:id>/', todo_list_detail, name='todo_list_detail'),
    path('add/', todo_list_add, name='todo_list_add'),
]

brain_two/todos/models.py
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey('TodoList', related_name='items', on_delete=models.CASCADE)


def __str__(self):
    return self.name

brain_two/todos/forms.py
from django import forms
from .models import TodoList


class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('name',)

brain_two/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoList
from .forms import TodoListForm
from datetime import date


def todo_list_list(request):
    todo_lists = TodoList.objects.all()
    return render(request, 'todos/todo_list_list.html', {'todo_lists': todo_lists})


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    context = {'todo_list': todo_list, 'current_date': date.today()}
    return render(request, 'todos/todo_list_detail.html', context)


def create_todo_list(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            list = form.save()
            return redirect("todo_list_detail", id=list.id)
    else:
        form = TodoListForm()
    return render(request, 'todos/create_todo_list.html', {'form': form})


def todo_list_add(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect("todo_list_detail", id=todo_list.id)
    else:
        form = TodoListForm()
    context = {'form': form}
    return render(request, 'todos/todo_list_add.html', context)

brain_two/todos/templates/todos/todo_list_detail.html
{% block content %}
  <h1>{{ todo_list.name }}</h1>
  <p>Number of items: {{ todo_list.items.count }}</p>
  
  <table>
    <thead>
      <tr>
        <th>Task</th>
        <th>Due Date</th>        
      </tr>
    </thead>
    <tbody>
      {% for item in todo_list.task.all %}
        <tr>
          <td>{{ task.name }}</td>          
          <td>
            {% if task.due_date %}
             {{ task.due_date|date:"F j, Y" }}
            {% endif %}
            </td>
        </tr>      
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

brain_two/todos/templates/todos/todo_list_list.html
{% block title %}Todo Lists{% endblock %}

{% block content %}
<main>
  <div>
    <h1>My Lists</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Number of items</th>
        </tr>
      </thead>
      <tbody>
        {% for todo_list in todo_lists %}
        <tr>
            <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
            <td>{{ todo_list.items.count }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="2">No lists yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}